--- GERENCIADOR INICIADO COM SUCESSO ---
 Arquivo 'documento_teste_erros (1)_dOTsL0s.docx' copiado para a pasta 'C:\Users\Danilo\Downloads\dossel_project\media\entrada'.

 Documento a processar: ['documento_teste_erros (1)_dOTsL0s.docx']
 Modo de revisão: completa
 E-mail destino: n.danilo@dosselambiental.com.br
 Progresso atualizado para: 5% (ID da Revisão: 41)

 Iniciando processamento paralelo de 'Scripts\Mapeador_Completo.py' para 1 documento(s).

 Executando: C:\Users\Danilo\Downloads\dossel_project\venv\scripts\python.exe -u Scripts\Mapeador_Completo.py documento_teste_erros (1)_dOTsL0s.docx --id_revisao 41
 Concluído OK: 'Scripts\Mapeador_Completo.py' para 'documento_teste_erros (1)_dOTsL0s.docx'
 Progresso atualizado para: 25% (ID da Revisão: 41)

 Iniciando processamento paralelo de 'Scripts\Processador_Final_Dossel.py' para 1 documento(s).

 Executando: C:\Users\Danilo\Downloads\dossel_project\venv\scripts\python.exe -u Scripts\Processador_Final_Dossel.py documento_teste_erros (1)_dOTsL0s --id_revisao 41
 Cancelamento detectado para a revisão 41.
 Cancelamento solicitado; encerrando subprocesso …
 Houve falhas durante o processamento paralelo de 'Scripts\Processador_Final_Dossel.py'.
 Falhas durante o processamento. O processo pode ter sido cancelado.
 Progresso atualizado para: 100% (ID da Revisão: 41)
 Gerenciador finalizou a execução.
