--- GERENCIADOR INICIADO COM SUCESSO ---
 Arquivo 'documento_teste_erros (1)_0hIZgXY.docx' copiado para a pasta 'C:\Users\Danilo\Downloads\dossel_project\media\entrada'.

 Documento a processar: ['documento_teste_erros (1)_0hIZgXY.docx']
 Modo de revisão: completa
 E-mail destino: n.danilo@dosselambiental.com.br
 Progresso atualizado para: 5% (ID da Revisão: 42)

 Iniciando processamento paralelo de 'Scripts\Mapeador_Completo.py' para 1 documento(s).

 Executando: C:\Users\Danilo\Downloads\dossel_project\venv\scripts\python.exe -u Scripts\Mapeador_Completo.py documento_teste_erros (1)_0hIZgXY.docx --id_revisao 42
 Concluído OK: 'Scripts\Mapeador_Completo.py' para 'documento_teste_erros (1)_0hIZgXY.docx'
 Progresso atualizado para: 25% (ID da Revisão: 42)

 Iniciando processamento paralelo de 'Scripts\Processador_Final_Dossel.py' para 1 documento(s).

 Executando: C:\Users\Danilo\Downloads\dossel_project\venv\scripts\python.exe -u Scripts\Processador_Final_Dossel.py documento_teste_erros (1)_0hIZgXY --id_revisao 42
 Cancelamento detectado para a revisão 42.
 Cancelamento solicitado; encerrando subprocesso …
 Houve falhas durante o processamento paralelo de 'Scripts\Processador_Final_Dossel.py'.
 Falhas durante o processamento. O processo pode ter sido cancelado.
 Progresso atualizado para: 100% (ID da Revisão: 42)
 Gerenciador finalizou a execução.
